name: .NET Core

on:
  push:
    branches: 
    - master
    - release/*

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
        
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: actions/checkout@v1
      
      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
       
      - name: Build Docker Image
        run: dotnet publish -c Release && docker build -t ${{ secrets.DOCKER_USERNAME }}/netcore-docker-demo:latest .
      
      - name: Push Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/netcore-docker-demo:latest
